cal/urls.py
# cal/urls.py

from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'', views.agenda, name='agenda'),
]

pacte/urls.py
from django.urls import path
from django.conf.urls import include, url
from pacte import views
from django.views.generic import TemplateView
from .views import handler400 as h400, handler403  as h403, handler404  as h404, handler500  as h500

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

urlpatterns = [
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^captcha/', include('captcha.urls')),
    path(r'agenda/', include('cal.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.bienvenue, name='bienvenue'),
    url(r'^bienvenue/$', views.bienvenue, name='bienvenue'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^gallerie/$', views.gallerie, name='gallerie'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/news/$', views.notifications_news, name='notifications_news'),
    url(r'^notificationsParDate/$', views.notificationsParDate, name='notificationsParDate'),
    url(r'^notificationsLues/$', views.notificationsLues, name='notificationsLues'),
    url(r'^dernieresInfos/$', views.dernieresInfos, name='dernieresInfos'),
    url(r'^site/presentation/$', views.presentation_site, name='presentation_site'),
    url(r'^gestion/', admin.site.urls, name='admin',),
    url(r'^merci/$', views.merci, name='merci'),
    url(r'^kit/', include('fiches.urls', namespace='pacte.fiches')),
    url(r'^chercher/produit/$', login_required(views.chercher), name='chercher'),
    url(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    url(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    url(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),
    url(r'^accounts/profil_inconnu/$', views.profil_inconnu, name='profil_inconnu', ),
    url(r'^accounts/profil_modifier/$', login_required(views.profil_modifier.as_view()), name='profil_modifier', ),
    url(r'^accounts/profil_supprimer/$', login_required(views.profil_supprimer.as_view()), name='profil_supprimer', ),
    url(r'^accounts/profil_contact/(?P<user_id>[0-9]+)/$', login_required(views.profil_contact), name='profil_contact', ),
    url(r'^register/$', views.register, name='senregistrer', ),
    url(r'^password/change/$', views.change_password, name='change_password'),
    path('auth/', include('django.contrib.auth.urls')),

    url(r'^contact_admins/$', views.contact_admins, name='contact_admins', ),
    url(r'^cgu/$', views.cgu, name='cgu', ),
    url(r'^liens/$', views.liens, name='liens', ),
    url(r'^fairedon/$', views.fairedon, name='fairedon', ),
    #url(r'^agenda/$', views.agenda, name='agenda',),
    url(r'^cooperateurs/annuaire/$', login_required(views.annuaire), name='annuaire', ),
    url(r'^cooperateurs/listeFollowers/$', login_required(views.listeFollowers), name='listeFollowers', ),
    url(r'^cooperateurs/carte/$', login_required(views.carte), name='carte', ),

    url(r'^conversations/(?P<destinataire>[-\w.]+)$', login_required(views.lireConversation), name='agora_conversation'),
    url(r'^conversations/(?P<destinataire1>[-\w.]+)/(?P<destinataire2>[-\w.]+)$', login_required(
        views.lireConversation_2noms), name='lireConversation_2noms'),
    url(r'^conversations/$', login_required(views.ListeConversations.as_view()), name='conversations'),
    url(r'^conversations/chercher/$', login_required(views.chercherConversation), name='chercher_conversation'),
    url(r'^suivre_conversation/$', views.suivre_conversations, name='suivre_conversations'),
    url(r'^agora/$', login_required(views.agora), name='agora_general'),
    url(r'^activity/', include('actstream.urls')),
    url(r'^inscription_newsletter/$', views.inscription_newsletter, name='inscription_newsletter', ),
    url(r'^modifierMessage/(?P<id>[0-9]+)(?P<type>[-\w.]+)$', views.modifier_message, name='modifierMessage'),
]


urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="pacte/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = h404
handler500 = h500
handler400 = h400
handler403 = h403

if settings.LOCALL:
    import debug_toolbar
    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)),] + urlpatterns
    #urlpatterns += url('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

pacte/views.py
# -*- coding: utf-8 -*-
'''
Created on 25 mai 2017

@author: tchenrezi
'''
from django.shortcuts import HttpResponseRedirect, render, redirect#, render, get_object_or_404, redirect, render_to_response,

from .forms import ContactForm, ProfilCreationForm, MessageForm, MessageGeneralForm, \
    ProducteurChangeForm, ChercherConversationForm, InscriptionNewsletterForm, \
    MessageChangeForm
from .models import Profil, Conversation, Message, MessageGeneral, getOrCreateConversation, Suivis, InscriptionNewsletter
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.core.mail import mail_admins, send_mail, BadHeaderError, send_mass_mail

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import Group, User
from django.views.decorators.csrf import csrf_exempt

from django.views.decorators.debug import sensitive_variables
#from django.views.decorators.debug import sensitive_post_parameters

#from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q, CharField
from django.db.models.functions import Lower
from django.utils.html import strip_tags

from actstream import actions, action
from actstream.models import Action, any_stream, following,followers


from django.utils.timezone import now

CharField.register_lookup(Lower, "lower")

#import sys
#from io import BytesIO
#from django.core.files.uploadedfile import InMemoryUploadedFile
#from PIL import Image
#from braces.views import LoginRequiredMixin

def handler404(request, *args, **kwargs):  #page not found
    response = render(request, "404.html")
    response.status_code = 404
    return response

def handler500(request, *args, **kwargs):   #erreur du serveur
    response = render(request, "500.html")
    response.status_code = 500
    return response

def handler403(request, *args, **kwargs):   #non autorisé
    response = render(request, "403.html")
    response.status_code = 403
    return response

def handler400(request, *args, **kwargs):   #requete invalide
    response = render(request, "400.html")
    response.status_code = 400
    return response

def bienvenue(request):
    return render(request, 'bienvenue.html', {})


def presentation_site(request):
    return render(request, 'presentation_site.html')

def gallerie(request):
    return render(request, 'gallerie.html')

def faq(request):
    return render(request, 'faq.html')


def merci(request, template_name='merci.html'):
    return render(request, template_name)


@login_required
def profil_courant(request, ):
    return render(request, 'profil.html', {'user': request.use})


@login_required
def profil(request, user_id):
    try:
        user = Profil.objects.get(id=user_id)
        distance = user.getDistance(request.user)
        return render(request, 'profil.html', {'user': user, 'distance':distance})
    except User.DoesNotExist:
            return render(request, 'profil_inconnu.html', {'userid': user_id})

@login_required
def profil_nom(request, user_username):
    try:
        user = Profil.objects.get(username=user_username)
        distance = user.getDistance(request.user)
        return render(request, 'profil.html', {'user': user, 'distance':distance})
    except User.DoesNotExist:
        return render(request, 'profil_inconnu.html', {'userid': user_username})

@login_required
def profil_inconnu(request):
    return render(request, 'profil_inconnu.html')

@login_required
def annuaire(request):
    profils = Profil.objects.filter(accepter_annuaire=True).order_by('username')
    nb_profils = len(Profil.objects.all())
    return render(request, 'annuaire.html', {'profils':profils, "nb_profils":nb_profils} )


@login_required
def listeContacts(request):
    if not request.user.is_permacat:
        return render(request, "notPermacat.html")
    listeMails = [
        {"type":'user_newsletter' ,"profils":Profil.objects.filter(inscrit_newsletter=True), "titre":"Liste des inscrits à la newsletter : "},
         {"type":'anonym_newsletter' ,"profils":InscriptionNewsletter.objects.all(), "titre":"Liste des inscrits anonymes à la newsletter : "},
      {"type":'user_adherent' , "profils":Profil.objects.filter(statut_adhesion=2), "titre":"Liste des adhérents : "},
        {"type":'user_futur_adherent', "profils":Profil.objects.filter(statut_adhesion=0), "titre":"Liste des personnes qui veulent adhérer à Permacat :"}
    ]
    return render(request, 'listeContacts.html', {"listeMails":listeMails})


@login_required
def listeFollowers(request):
    if not request.user.is_permacat:
        return render(request, "notPermacat.html")
    listeArticles = []
    # for art in Projet.objects.all():
    #     suiveurs = followers(art)
    #     if suiveurs:
    #         listeArticles.append({"titre": art.titre, "url": art.get_absolute_url(), "followers": suiveurs, })

    return render(request, 'listeFollowers.html', {"listeArticles":listeArticles})

@login_required
def carte(request):
    profils = Profil.objects.filter(accepter_annuaire=1)
    return render(request, 'carte_cooperateurs.html', {'profils':profils, 'titre': "La carte des coopérateurs*" } )


@login_required
def profil_contact(request, user_id):
    recepteur = Profil.objects.get(id=user_id)
    if request.method == 'POST':
        form = ContactForm(request.POST or None, )
        if form.is_valid():
            sujet = "[permacat] "+ request.user.username + "(" + request.user.email+ ") vous a écrit: "+ form.cleaned_data['sujet']
            message_txt = ""
            message_html = form.cleaned_data['msg']
            recepteurs = [recepteur.email,]
            if form.cleaned_data['renvoi'] :
                recepteurs = [recepteur.email, request.user.email]

            send_mail(
                sujet,
                message_txt,
                request.user.email,
                recepteurs,
                html_message=message_html,
                fail_silently=False,
                )
            return render(request, 'contact/message_envoye.html', {'sujet': form.cleaned_data['sujet'], 'msg':message_html, 'envoyeur':request.user.username + " (" + request.user.email + ")", "destinataire":recepteur.username + " (" +recepteur.email+ ")"})
    else:
        form = ContactForm()
    return render(request, 'contact/profil_contact.html', {'form': form, 'recepteur':recepteur})


def contact_admins(request):
    if request.method == 'POST':
        form = ContactForm(request.POST or None, )
        if form.is_valid():
            sujet = form.cleaned_data['sujet']
            message_txt = request.user.username + "(" + request.user.email + ") a envoyé le message suivant : "
            message_html = form.cleaned_data['msg']
            try:
                mail_admins(sujet, message_txt, html_message=message_html)
                if form.cleaned_data['renvoi']:
                    send_mail(sujet, "Vous avez envoyé aux administrateurs du site www.perma.cat le message suivant : " + message_html, request.user.email, [request.user.email,], fail_silently=False, html_message=message_html)

                return render(request, 'contact/message_envoye.html', {'sujet': sujet, 'msg': message_html,
                                                       'envoyeur': request.user.username + " (" + request.user.email + ")",
                                                       "destinataire": "administrateurs "})
            except BadHeaderError:
                return render(request, 'erreur.html', {'msg':'Invalid header found.'})

            return render(request, 'erreur.html', {'msg':"Désolé, une ereur s'est produite"})
    else:
        form = ContactForm()
    return render(request, 'contact/contact.html', {'form': form, "isContactProducteur":False})

@login_required
class profil_modifier_user(UpdateView):
    model = Profil
    form_class = ProducteurChangeForm
    template_name_suffix = '_modifier'
    fields = ['username', 'first_name', 'last_name', 'email', 'site_web', 'description', 'competences', 'pseudo_june', 'accepter_annuaire', 'inscrit_newsletter']

    def get_object(self):
        return Profil.objects.get(id=self.request.user.id)


class profil_modifier(UpdateView):
    model = Profil
    form_class = ProducteurChangeForm
    template_name_suffix = '_modifier'
    #fields = ['username','email','first_name','last_name', 'site_web','description', 'competences', 'inscrit_newsletter']

    def get_object(self):
        return Profil.objects.get(id=self.request.user.id)

class profil_supprimer(DeleteView):
    model = Profil
    success_url = reverse_lazy('bienvenue')

    def get_object(self):
        return Profil.objects.get(id=self.request.user.id)

@sensitive_variables('password')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/password_changer_form.html', {
        'form': form
    })

@sensitive_variables('user', 'password1', 'password2')
def register(request):
    if request.user.is_authenticated:
        return render(request, "erreur.html", {"msg":"Vous etes déjà inscrit et authentifié !"})

    form_profil = ProfilCreationForm(request.POST or None)
    if form_profil.is_valid():
        profil_courant = form_profil.save(commit=False,is_active = False)
        if profil_courant.statut_adhesion == 2:

pacte/templates/agora.html
{% extends 'base.html' %}
{% load blog_filters %}
{%block message%}{%endblock%}
{% block subtitle %}

<div class="row">
<div class="col-sm-12 textcenter">
    <h3>Salon public</h3>
</div>
</div>

{% endblock %}
{% block content %}

{% include 'salon.html' %}

{% endblock %}

pacte/templates/annuaire.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<script src="{% static 'js/sorttable.js' %}"></script>
{% endblock %}
{% block title %}Coopérateurs
{% endblock %}
{% block subtitle %}
<div class="row">
    <div class="col-sm-12 textcenter">
    <h3>Les adhérents au site* ({{profils|length}}/{{nb_profils}})</h3>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 textcenter">
        <div class="btn-group btn-group-justified">
            {% if request.user.is_permacat %}
            <a href="{% url 'annuaire_permacat' %}" >
                <button type="button" class="btn btn-primary" >Liste des adhérents Permacat</button>
                </a>
            {% endif %}
            {% if request.user.is_rtg %}
            <a href="{% url 'annuaire_rtg' %}" >
                <button type="button" class="btn btn-primary" >Liste des adhérents RameneTaGraine</button>
                </a>
            {% endif %}
            <a href="{% url 'carte' %}" >
                <button type="button" class="btn btn-primary" >Carte des inscrits</button>
            </a>
        </div>
    </div>
</div>

{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-12">
        <div style="overflow-x:auto;">
    <table class="table table-condensed tableprofils table-striped sortable">
        <thead class="thead-inverse">
            <tr>
                <th>Pseudo</th>
                <th>Email</th>
                <th>Code postal</th>
                <th>Commune</th>
            </tr>
        </thead>
        <tbody>
        {% for profil in profils %}
        <tr>
           {%comment%} <td>
                <img src="{{ profil.avatar.get_absolute_url }}" alt="pas d'image" style="width:100px;height:100px" href="{% url 'profil' profil.id %}">
            </td>
            {%endcomment%}
            <td><a href="{% url 'profil' profil.id %}">{{ profil.username }}</a></td>
            <td><a href="{% url 'profil' profil.id %}">{{ profil.email }}</a></td>
            <td><a href="{% url 'profil' profil.id %}">{{ profil.adresse.code_postal }}</a></td>
            <td><a href="{% url 'profil' profil.id %}">{{ profil.adresse.commune }}</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    </div>
    </div>

    <p class="textcenter textepetit">(*qui ont accepté d'apparaitre dans l'annuaire)</p>
{% endblock %}

pacte/templates/bienvenue.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load fontawesome %}
{%block header %}
 <script src="{% static 'js/cookielaw.js'%}" type="text/javascript"></script>
{%endblock%}
{% block subtitle %}
<div class="row">
	<div class="col-md-12">
		<h4 class = "textcenter rowbienvenue">{% trans "Bienvenue sur le site Perma.Cat !" %}</h4>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="row textcenter">
			<div class="col">
				<a  href="{% url 'gallerie' %}" ><img class="imgbienvenue" src="{{STATIC_URL}}{{nomImage}}" alt="gallerie" ></a>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="row">
			<div class="col-md-12">
				{% if nbExpires %}
					<hr>
					<div class="row" >
					  <div class="col-sm-12 textcenter" style ="color:#0f7407;">
						  <b><a href="{% url 'supprimerProduits_expires_confirmation' %}">Vous avez {{nbExpires}} offre{{nbExpires|pluralize:",s"}} du marché qui {{nbExpires|pluralize:"a,ont"}}  expiré. Cliquez ici pour l{{nbExpires|pluralize:"a,es"}} supprimer ou l{{nbExpires|pluralize:"a,es"}}  modifier</a></b>
					  </div>
					</div>
				{%endif%}

				 {% if not request.user.is_authenticated %}
					<hr>
					<div class="row" >
					  <div class="col-sm-12 textcenter">
						  <b> <a href="{% url 'inscription_newsletter' %}" class="btn btn-light btn-radius"><i class="fa fa-envelope-o"></i> S'inscrire à la newsletter...</a>

						  </b>
					  </div>
					</div>

				{%else%}
					<hr>
					<div class="row" >
					  <div class="col-sm-12 textcenter" style ="color:#0f7407;">
						{% if nbNotif %}
						  <b><a href="{% url 'notifications_news' %}">{% fontawesome_icon 'bell' %}  Vous avez {{nbNotif}} nouvelle{{ nbNotif|pluralize:",s" }} notification{{ nbNotif|pluralize:",s" }} depuis le {{request.user.date_notifications|date:"d/m/Y"}} à {{request.user.date_notifications|date:"G:i"}})</a></b>

						{%else%}
						  <b><a href="{% url 'notifications_news' %}">{% fontawesome_icon 'bell' %}  Notifications</a></b>
						{%endif%}
					  </div>
					</div>

					<hr>
					<div class="row" >
					  <div class="col-sm-12 textcenter">
						  <b><a href="{% url 'cal:agenda' %}">{% fontawesome_icon 'calendar' %} Agenda</a></b>
					  </div>
					</div>

				{% endif %}

				<hr>
			</div>
		</div>
	</div>
</div>


{% endblock %}


{% block content %}



{% load cookielaw_tags %}
{% cookielaw_banner %}

{% endblock %}

pacte/templates/erreur.html
{% extends 'base.html' %}
{% block subtitle %}Une erreur s'est produite : {{msg}}
{% endblock %}

pacte/templates/fairedon.html
{% extends 'base.html' %}
{% block subtitle %}
<iframe id="haWidget" allowtransparency="true" scrolling="auto" src="https://www.helloasso.com/associations/permaculture-catalane/formulaires/1/widget" style="width:100%;height:750px;border:none;" onload="window.scroll(0, this.offsetTop)"></iframe>
{% endblock %}

pacte/templates/liens.html
{% extends 'base.html' %}
{% block subtitle %}Liens intéressants à nos yeux : {% endblock %}

{% block content %}
<div class="row">
<div class="col">
    <ul class="list-group">
{%for lien in liens%}
        <li class="list-group-item" ><a href="{{lien}}" rel="external" target="_blank">{{lien}}</a></li>
{%endfor%}
</ul>
</div>
</div>
 {% endblock %}

pacte/templates/lireConversation.html
{% extends 'base.html' %}
{% load blog_filters %}
{%block message%}{%endblock%}
{% block subtitle %}
<div class="row">
<div class="col-sm-4">
    <a href="{% url 'conversations' %}" class="btn btn-info"> <i class="fa fa-arrow-left"></i> Conversations </a>
</div>
    <div class="col-sm-8">
Messages échangés avec <span style="background-color:PapayaWhip;"><a href="{% url 'profil_nom' destinataire  %}"> {{ destinataire }} </a></span> depuis le {{ conversation.date_creation|date:"SHORT_DATE_FORMAT"}}
    </div>
</div>
{% endblock %}
{% block content %}

<div class="contenu conversation" id="idConversation">
{% for mess in messages_echanges %}

    {% ifchanged %}
    <div class="row msg-date">
        <div class="col-sm-12">
            <p class="infos textcenter">{{ mess.date_creation|date:"DATE_FORMAT" }}</p>
        </div>
    </div>
    {% endifchanged %}
    <div class="row {% if mess.auteur.id == request.user.id %} msg-auteur  {%else%} msg-destinataire{%endif%}">
        <div class="col-sm-2 col-md-3 col-lg-1">
            <p class="infos  textepetit">
                {{ mess.date_creation|date:"G:i" }} {% ifchanged %}, <a href="{% url 'profil' mess.auteur.id %}"> {{mess.auteur}}</a>{% endifchanged %}
            {% if request.user == mess.auteur %}
                <a class="boutonediter" href="{{ mess.get_edit_url  }}" role="button"><i class="fa fa-edit"></i></a>
            {% endif %}
            </p>
        </div>
        <div class=" col-sm-8 col-md-9 col-lg-10 message ">
                <p>{{ mess.message|safe|url }}</p>
        </div>
    </div>

{% endfor %}
</div>
    <script>
    var messageBody = document.querySelector('#idConversation');
    messageBody.scrollTop = idConversation.scrollHeight - idConversation.clientHeight;
</script>

<hr>
<h5>Répondre : </h5>
<div>
    <input type="hidden" name="Nouveau Message" value="{{ message }}">

<div>
<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="Nouveau Message" value="{{ message_defaut }}">
    {% include 'form_template3.html'  with boutonAnnuler=False %}
</form>
</div>


{% endblock %}

pacte/templates/listeFollowers.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<script src="{% static 'js/sorttable.js' %}"></script>
{% endblock %}
{% block title %}
Coopérateurs
{% endblock %}
{% block subtitle %}
<div class="row">
    <div class="col-sm-12 textcenter">
        <h3>Liste de tous les articles/projets suivis</h3>
    </div>
</div>

{% endblock %}
{% block content %}

{% for article in listeArticles %}
<div class="row justify-content-center">
    <div class="col-sm-6 ">
        <p> <a href="{{article.url}}">{{article.titre}} : </a>
        {%for user in article.followers%}
            {{user.username}}
            {% if not forloop.last %}, {% endif%}
        {%endfor%}
        </p>
    </div>
</div>
<hr>
{%endfor%}

{% endblock %}

pacte/templates/merci.html
{% extends 'base.html' %}
{% block subtitle %}Merci !{% endblock %}

pacte/templates/profil_inconnu.html
{% extends 'base.html' %} 
{% block title %}Profil inconnu ({{userid}}) {% endblock %}
{% block subtitle %}
Désolé, le profil ({{userid}}) que vous recherchez n'existe pas (ou plus)...
{% endblock %}

pacte/templates/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}S'enregistrer{% endblock %}
{%block message%}
{%endblock%}
{% block content %}

<div class="jumbotron">
    <div class="row justify-content-sm-center">
        <h4>Renseignez les informations suivantes pour vous inscrire (les champs avec (*) sont obligatoires)</h4>
    </div>
    <div class="row justify-content-sm-center">
        <h6><a href="https://permacat.herokuapp.com/register/">Lien vers l'inscription sécurisée</a></h6>
    </div>
    <div class="row justify-content-sm-center">
        <div class="col-sm-12 col-md-10 col-lg-8 ">
            <form role="form" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
                {%include 'form_template2.html' with form=form_profil%}
                {%include 'form_template2.html' with form=form_adresse%}


          <button type="submit" class="btn btn-success">S'enregistrer</button>
        </form>
        </div>
    </div>
</div>


    {% endblock %}

pacte/templates/userenattente.html
{% extends 'base.html' %}
{% block navbar%}
{% endblock %}
{% block content %}
<h2 class="textcenter">Merci pour votre intérêt. Votre compte a été créé!
    </h2>
<p>
{%if user.is_permacat %}
Comme vous êtes un membre de l'association permacat, votre compte doit être validé par l'administrateur avant d'être disponible.
Contactez l'administrateur du site, en cas de souci.
{%else%}
Vous pouvez consulter les annonces, en publier, et discuter avec les autres !

 <a href="{% url 'login' %}">
        <button type="button" class="btn btn-secondary" >
               Se connecter...
            </button>
{%endif%}
</p>
{% endblock %}