cal/urls.py
# cal/urls.py

from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'', views.agenda, name='agenda'),
]

fiches/urls.py
# -*- coding: utf-8 -*-
"""Pacte URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog__ import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog__/', include(blog_urls))
"""
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'fiches'

urlpatterns = [
    url(r'^accueil-fiches/$', login_required(views.accueil), name="acceuil"),
    url(r'^fiches/$', login_required(views.ListeFiches.as_view(), login_url='/auth/login/'), name="index"),
    url(r'^ateliers/$', login_required(views.ListeAteliers.as_view(), login_url='/auth/login/'), name="index_ateliers"),
    url(r'^fiche/(?P<slug>[-\w]+)$', views.lireFiche, name='lireFiche'),
    url(r'^atelier/(?P<slug>[-\w]+)$', views.lireAtelier, name='lireAtelier'),
    url(r'^atelier/id/(?P<id>[-\w]+)$', views.lireAtelier_id, name='lireAtelier_id'),
    url(r'^modifierFiche/(?P<slug>[-\w]+)$', login_required(views.ModifierFiche.as_view(), login_url='/auth/login/'), name='modifierFiche'),
    url(r'^modifierAtelier/(?P<slug>[-\w]+)$', login_required(views.ModifierAtelier.as_view(), login_url='/auth/login/'), name='modifierAtelier'),
    url(r'^supprimerFiche/(?P<slug>[-\w]+)$', login_required(views.SupprimerFiche.as_view(), login_url='/auth/login/'), name='supprimerFiche'),
    url(r'^ajouterFiche/$', login_required(views.ajouterFiche), name='ajouterFiche'),
    url(r'^ajouterAtelier/(?P<fiche_slug>[-\w]+)$', login_required(views.ajouterAtelier), name='ajouterAtelier'),
    url(r'^voirFicheTest/$', views.voirFicheTest, name='voirFicheTest'),

]

pacte/urls.py
from django.urls import path
from django.conf.urls import include, url
from pacte import views
from django.views.generic import TemplateView
from .views import handler400 as h400, handler403  as h403, handler404  as h404, handler500  as h500

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

urlpatterns = [
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^captcha/', include('captcha.urls')),
    path(r'agenda/', include('cal.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.bienvenue, name='bienvenue'),
    url(r'^bienvenue/$', views.bienvenue, name='bienvenue'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^gallerie/$', views.gallerie, name='gallerie'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/news/$', views.notifications_news, name='notifications_news'),
    url(r'^notificationsParDate/$', views.notificationsParDate, name='notificationsParDate'),
    url(r'^notificationsLues/$', views.notificationsLues, name='notificationsLues'),
    url(r'^dernieresInfos/$', views.dernieresInfos, name='dernieresInfos'),
    url(r'^site/presentation/$', views.presentation_site, name='presentation_site'),
    url(r'^gestion/', admin.site.urls, name='admin',),
    url(r'^merci/$', views.merci, name='merci'),
    url(r'^kit/', include('fiches.urls', namespace='pacte.fiches')),
    url(r'^chercher/produit/$', login_required(views.chercher), name='chercher'),
    url(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    url(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    url(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),
    url(r'^accounts/profil_inconnu/$', views.profil_inconnu, name='profil_inconnu', ),
    url(r'^accounts/profil_modifier/$', login_required(views.profil_modifier.as_view()), name='profil_modifier', ),
    url(r'^accounts/profil_supprimer/$', login_required(views.profil_supprimer.as_view()), name='profil_supprimer', ),
    url(r'^accounts/profil_contact/(?P<user_id>[0-9]+)/$', login_required(views.profil_contact), name='profil_contact', ),
    url(r'^register/$', views.register, name='senregistrer', ),
    url(r'^password/change/$', views.change_password, name='change_password'),
    path('auth/', include('django.contrib.auth.urls')),

    url(r'^contact_admins/$', views.contact_admins, name='contact_admins', ),
    url(r'^cgu/$', views.cgu, name='cgu', ),
    url(r'^liens/$', views.liens, name='liens', ),
    url(r'^fairedon/$', views.fairedon, name='fairedon', ),
    #url(r'^agenda/$', views.agenda, name='agenda',),
    url(r'^cooperateurs/annuaire/$', login_required(views.annuaire), name='annuaire', ),
    url(r'^cooperateurs/listeFollowers/$', login_required(views.listeFollowers), name='listeFollowers', ),
    url(r'^cooperateurs/carte/$', login_required(views.carte), name='carte', ),

    url(r'^conversations/(?P<destinataire>[-\w.]+)$', login_required(views.lireConversation), name='agora_conversation'),
    url(r'^conversations/(?P<destinataire1>[-\w.]+)/(?P<destinataire2>[-\w.]+)$', login_required(
        views.lireConversation_2noms), name='lireConversation_2noms'),
    url(r'^conversations/$', login_required(views.ListeConversations.as_view()), name='conversations'),
    url(r'^conversations/chercher/$', login_required(views.chercherConversation), name='chercher_conversation'),
    url(r'^suivre_conversation/$', views.suivre_conversations, name='suivre_conversations'),
    url(r'^agora/$', login_required(views.agora), name='agora_general'),
    url(r'^activity/', include('actstream.urls')),
    url(r'^inscription_newsletter/$', views.inscription_newsletter, name='inscription_newsletter', ),
    url(r'^modifierMessage/(?P<id>[0-9]+)(?P<type>[-\w.]+)$', views.modifier_message, name='modifierMessage'),
]


urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="pacte/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = h404
handler500 = h500
handler400 = h400
handler403 = h403

if settings.LOCALL:
    import debug_toolbar
    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)),] + urlpatterns
    #urlpatterns += url('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

fiches/models.py
from django.db import models
from pacte.models import Profil, Suivis
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
import uuid

class Choix():
    statut_fiche = ('0','En préparation'), ("1","Intégrée dans le kit"), ('2','En attente' ),
    type_fiche = ('0','Bases de la permaculture'), ('1',"Conception du jardin"), ('2','Réalisation du jardin'), ('3','Récolter'),
    couleurs_fiches = {
        '2':'#4DC490', '1':'#C0EDA0', '3':'#00AA8B', '0':'#FCE79C',
        # '0':"#e0f7de", '1':"#dcc0de",
        # '5':"#d1ecdc",'3':"#fcf6bd", '4':"#d0f4de", '7':"#fff2a0",
        # '9':"#ffc4c8", '2':"#bccacf", '10':"#87bfae", '11':"#bcb4b4"
    }
    statut_fiche = ('0', 'proposition'), ('1', "en cours d'écriture"), ("2", "achevée mais pas validée"), ("3", "validée")
    type_difficulte = ('0', 'facile'), ('1', "moyen"), ("2", "difficile")
    type_jauge = ('1', "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")
    type_budget = ('0', "0"), ('1', "1"), ("2", "2"), ("3", "3")
    type_temps = ('1', "1h"), ("2", "2h"), ("3", "3h"), ("4", "4h"), ("5", "6h"), ("6", "1 journée"),  ("7", "plusieurs jours"),  ("8", "plusieurs mois"),
    type_age = ('0', '3-6 ans'), ('1', "7-11 ans"), ("2", "12 ans et plus"), ("3", "3-11ans"), ("4", "Tout public")
    type_atelier = ('0', 'Observation'), ('1', "Experience"), ("2", "Jardinage")

    def get_categorie(num):
        return Choix.type_fiche[int(num)][1]

    def get_difficulte(num):
        return Choix.type_difficulte[int(num)][1]

    def get_age(num):
        return Choix.type_fiche[int(num)][1]

    def get_typeAtelier(num):
        return Choix.type_atelier[int(num)][1]

    def get_couleur_cat(cat):
            return Choix.couleurs_fiches[cat]

class Fiche(models.Model):
    categorie = models.CharField(max_length=30,         
        choices=(Choix.type_fiche),
        default='0', verbose_name="categorie")
    statut = models.CharField(max_length=30,
        choices=(Choix.statut_fiche),
        default='proposition', verbose_name="statut de la fiche")
    numero = models.PositiveIntegerField(blank=False, default=1)
    titre = models.CharField(max_length=120)
    slug = models.SlugField(max_length=100, default=uuid.uuid4)
    contenu = models.TextField(null=True, blank=True)
    objectif = models.TextField(null=True, blank=True)
    en_savoir_plus = models.TextField(null=True, blank=True,)


    date_creation = models.DateTimeField(verbose_name="Date de parution", default=timezone.now)
    date_modification = models.DateTimeField(verbose_name="Date de modification", default=timezone.now)

    date_dernierMessage = models.DateTimeField(verbose_name="Date du dernier message", auto_now=True)
    dernierMessage = models.CharField(max_length=100, default=None, blank=True, null=True)

    tags = TaggableManager(verbose_name=("Mots-clés"), help_text=("Une liste de mots clés, séparés par des virgules."), blank=True,)

    class Meta:
        ordering = ('-date_creation', )
        
    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('fiches:lireFiche', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.date_creation = timezone.now()
        return super(Fiche, self).save(*args, **kwargs)

    @property
    def get_couleur(self):
            return Choix.couleurs_fiches[self.categorie]

    @property
    def get_couleur_cat(self,cat):
            return Choix.couleurs_fiches[cat]


class Atelier(models.Model):
    categorie = models.CharField(max_length=30,
                                 choices=(Choix.type_atelier),
                                 default='0', verbose_name="categorie")
    titre = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, default=uuid.uuid4)
    contenu = models.TextField(null=True)
    age = models.CharField(max_length=30,
                                 choices=(Choix.type_age),
                                 default='0', verbose_name="age")
    difficulte = models.CharField(max_length=30,
                                 choices=(Choix.type_difficulte),
                                 default='0', verbose_name="difficulté")
    budget = models.CharField(max_length=30,
                                 choices=(Choix.type_budget),
                                 default='0', verbose_name="budget")
    temps = models.CharField(max_length=30,
                                 choices=(Choix.type_temps),
                                 default='0', verbose_name="temps")
    fiche = models.ForeignKey(Fiche, on_delete=models.CASCADE,)
    date_creation = models.DateTimeField(verbose_name="Date de parution", default=timezone.now)
    date_modification = models.DateTimeField(verbose_name="Date de modification", default=timezone.now)

    class Meta:
        ordering = ('-date_creation',)

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('fiches:lireFiche', kwargs={'slug': self.slug})

    def save(self, commit=False, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.date_creation = timezone.now()
        return super(Atelier, self).save(*args, **kwargs)

    @property
    def get_couleur(self):
        try:
            return Choix.couleurs_fiches[self.categorie]
        except:
            return Choix.couleurs_fiches["11"]
    #
    # @property
    # def get_difficulte(self):
    #     return Choix.type_difficulte[int(self.difficulte)][1]

    # @property
    # def get_budget_html(self):
    #     return "{% fontawesome_icon 'euro-sign' %}"
    #     return "{% fontawesome_icon 'euro-sign' %} ".join([" " for i in range(int(self.budget))])

    @property
    def get_budget_length(self):
        return range(int(self.budget))

    @property
    def get_budget(self):
        return int(self.budget)

    @property
    def get_temps_length(self):
        return range(int(self.temps))

class CommentaireFiche(models.Model):
    auteur_comm = models.ForeignKey(Profil, on_delete=models.CASCADE)
    commentaire = models.TextField()
    fiche = models.ForeignKey(Fiche, on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.__str__()

    def __str__(self):
        return "(" + str(self.id) + ") "+ str(self.auteur_comm) + ": " + str(self.fiche)

fiches/forms.py
from django import forms
from .models import Fiche, CommentaireFiche, Atelier
from django.utils.text import slugify
import itertools
from django_summernote.widgets import SummernoteWidget

class FicheForm(forms.ModelForm):
    objectif = forms.CharField(label="Objectif de la fiche", strip=False)

    class Meta:
        model = Fiche
        fields = ['categorie', 'numero', 'titre', 'objectif', 'contenu', 'en_savoir_plus', 'tags']
        widgets = {
            'contenu': SummernoteWidget(),
            'en_savoir_plus': SummernoteWidget(),
        }

    def save(self, userProfile):
        instance = super(FicheForm, self).save(commit=False)

        max_length = Fiche._meta.get_field('slug').max_length
        instance.slug = orig = slugify(instance.titre)[:max_length]

        for x in itertools.count(1):
            if not Fiche.objects.filter(slug=instance.slug).exists():
                break

            # Truncate the original slug dynamically. Minus 1 for the hyphen.
            instance.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)

        instance.save()
        try:
            instance.save_m2m()
        except:
            pass

        return instance


    def __init__(self, request, *args, **kwargs):
        super(FicheForm, self).__init__(request, *args, **kwargs)
        self.fields['contenu'].strip = False

class FicheChangeForm(forms.ModelForm):
    objectif = forms.CharField(label="Objectif de la fiche", strip=False)


    class Meta:
        model = Fiche
        fields = ['categorie', 'numero', 'titre', 'objectif', 'contenu', 'en_savoir_plus', 'tags']
        widgets = {
            'contenu': SummernoteWidget(),
            'en_savoir_plus': SummernoteWidget(),
        }


    def __init__(self, *args, **kwargs):
        super(FicheChangeForm, self).__init__(*args, **kwargs)
        self.fields['contenu'].strip = False

class AtelierForm(forms.ModelForm):
    class Meta:
        model = Atelier
        fields = ['categorie', 'titre', 'contenu' ,'age' ,'difficulte' ,'budget' ,'temps']
        widgets = {
            'contenu': SummernoteWidget(),
           # 'bar': SummernoteInplaceWidget(),
        }

    def save(self, fiche):
        instance = super(AtelierForm, self).save(commit=False)

        instance.fiche = fiche
        max_length = Atelier._meta.get_field('slug').max_length
        instance.slug = orig = slugify(instance.titre)[:max_length]

        for x in itertools.count(1):
            if not Atelier.objects.filter(slug=instance.slug).exists():
                break

            # Truncate the original slug dynamically. Minus 1 for the hyphen.
            instance.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)

        instance.save()

        return instance


    def __init__(self, request, *args, **kwargs):
        super(AtelierForm, self).__init__(request, *args, **kwargs)
        self.fields['contenu'].strip = False

class AtelierChangeForm(forms.ModelForm):

    class Meta:
        model = Atelier
        fields = ['categorie', 'titre', 'contenu', 'age' ,'difficulte' ,'budget' ,'temps']
        widgets = {
            'contenu': SummernoteWidget(),
        }


    def __init__(self, *args, **kwargs):
        super(AtelierChangeForm, self).__init__(*args, **kwargs)
        self.fields['contenu'].strip = False


class CommentaireFicheForm(forms.ModelForm):
    commentaire = forms.CharField(widget=forms.Textarea(attrs={'rows': 1}), label='Laisser un commentaire...')

    class Meta:
        model = CommentaireFiche
        exclude = ['fiche','auteur_comm']
        #
        #widgets = {
         #  'commentaire': SummernoteWidget(),
        #        'commentaire': forms.Textarea(attrs={'rows': 1}),
         #   }

    def __init__(self, request, *args, **kwargs):
        super(CommentaireFicheForm, self).__init__(request, *args, **kwargs)
        self.fields['commentaire'].strip = False

fiches/templates/fiches/atelier_modifier.html
{% extends 'base.html' %}
{% block title %}Modifier l'atelier{% endblock %}
{% block subtitle %}
<h3>Modifier l'atelier</h3>

{% endblock %}
{% block content %}

<div class="row-sm-12 row-lg-6 mx-auto">
    {% include 'form_template.html'%}
</div>


{% endblock %}

{% block comment %}{% endblock %}

fiches/templates/fiches/atelier_template.html
{% load fontawesome %}
{% load fiches_filters %}

<div class="row liste_atelier">
    <div class="col justify-content-center">
    <div class="row">
        <div class="col-sm-12 col-md-8  textcenter">
            <p> <h3><a href="{% url 'fiches:lireAtelier' slug=atelier.slug %}">{{ atelier.titre }}</a>
        </h3></p>
        </div>
        <div class="col-sm-12 col-md-4 textcenter">
            <table class="greenTable">
<thead>
<tr>
<th>Age</th>
<th>Difficulté</th>
<th>Budget</th>
<th>Temps</th>
</tr>
</thead>
<tbody>
<tr>
    <td>{{ atelier.get_age_display }}</td><td>{{ atelier.get_difficulte_display }}</td><td>

      <img  style="max-width: 80%; height: auto;" src="{{STATIC_URL}}img/monnaie{{atelier.get_budget}}.png" alt="cout"/>
    {%for i in atelier.get_budget_length %}
               {% fontawesome_icon 'coins' %}
               {% comment %}{% fontawesome_icon 'euro-sign' %} {% endcomment %}
    {%endfor%}

</td>
    <td>
        {{ atelier.get_temps_display }}
         {% comment %}
    {%for i in atelier.get_temps_length %}
               {% fontawesome_icon 'link' %}
               {% fontawesome_icon 'clock' %}
    {%endfor%}
         {% endcomment %}
</td>
</tr>
</tbody>
</tr>
</table>

        </div>
    </div>
         {% comment %}
    <div class="row">
        <div class="col-sm-12 ">
            <p>{{ atelier.contenu|safe}}</p>
        </div>
    </div>
         {% endcomment %}
</div>
</div>

fiches/templates/fiches/lireAtelier.html
{% extends 'base2.html' %}
{% load fiches_filters %}
{% load blog_filters %}
{% load fontawesome %}
{% block subtitle %}


{% endblock %}

{% block navbar%}
{%if not request.user.is_authenticated %}
{% else %}
            {% include 'navigationBar.html' %}
{% endif %}
{% endblock%}
{% block content %}

 <div class="row justify-content-center">
    <div class="col-sm-2">

        <div class="btn-group btn-group-justified">
        <a  href="{%if request.user.is_authenticated %}{% url 'fiches:index_ateliers' %}{% endif %}">
        <button class="btn btn-info btn-sm textright" ><i class="fa fa-arrow-left"></i> Ateliers</button>
            </a>
        </div>
    </div>
    <div class="col-sm-8">
        <p class="infos  textepetit textcenter "><a href="{%if request.user.is_authenticated %}{% url 'fiches:lireFiche' slug=atelier.fiche.slug %}{%else%}{% url 'fiches:voirFicheTest' %}{%endif%}"><i class="fa fa-arrow-left"></i> Fiche: {{ atelier.fiche.titre }} </a>
        </p>
    </div>
        <div class="col-sm-2 textright">
            <a href="{%if request.user.is_authenticated %}{% url 'fiches:modifierAtelier' slug=atelier.slug %}{% endif %}">
               <button type="button" class="btn btn-sm btn-warning">
                 &nbsp;Modifier
               </button></a>
        </div>
 </div>



    <div class="row contenu atelier">
    <div class="col justify-content-center">


    <div class="row titre_fiche" style="background-color:{{atelier.fiche.get_couleur}};margin-bottom:15px;">
        <div class="col textcenter" >
              <h2> Atelier : {{ atelier.titre }}</h2>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-4 textcenter">
            <table class="greenTable">
<thead>
<tr>
<th>Age</th>
<th>Difficulté</th>
<th>Budget</th>
<th>Temps</th>
</tr>
</thead>
<tbody>
<tr>
    <td>{{ atelier.get_age_display }}</td><td>{{ atelier.get_difficulte_display }}</td><td>

      <img  style="max-width: 80%; height: auto;" src="{{STATIC_URL}}img/monnaie{{atelier.get_budget}}.png" alt="cout"/>
    {%for i in atelier.get_budget_length %}
               {% fontawesome_icon 'coins' %}
               {% comment %}{% fontawesome_icon 'euro-sign' %} {% endcomment %}
    {%endfor%}

</td>
    <td>
        {{ atelier.get_temps_display }}
         {% comment %}
    {%for i in atelier.get_temps_length %}
               {% fontawesome_icon 'link' %}
               {% fontawesome_icon 'clock' %}
    {%endfor%}
         {% endcomment %}
</td>
</tr>
</tbody>
</tr>
</table>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 ">
            <p>{{ atelier.contenu|safe}}</p>
        </div>
    </div>
</div>
</div>
        </div>



{% endblock %}

fiches/templates/fiches/lireFiche.html
{% extends 'base2.html' %}
{% load fiches_filters %}
{% load blog_filters %}
{% load fontawesome %}
{% block subtitle %}


{% endblock %}
            {% block navbar%}
{%if not request.user.is_authenticated %}
{% else %}
            {% include 'navigationBar.html' %}
{% endif %}
            {% endblock%}
{% block content %}

 <div class="row justify-content-center">

    <div class="col-sm-2">

        <a  href="{%if request.user.is_authenticated %}{% url 'fiches:index'  %}{% endif %}">
        <button class="btn btn-info btn-sm textright" ><i class="fa fa-arrow-left"></i> Sommaire</button>
            </a>

    </div>
    <div class="col-sm-8">
        <p class="infos  textepetit textcenter "><a href="{%if request.user.is_authenticated %}{% url 'fiches:index'  %}?categorie={{fiche.categorie}}{% endif %}">{{ fiche.get_categorie_display }}</a>, {{ fiche.date_creation|date:"DATE_FORMAT" }}

        </p>
    </div>
        <div class="col-sm-2 textright">
            <a href="{%if request.user.is_authenticated %}{% url 'fiches:modifierFiche' slug=fiche.slug %}{% endif %}">
               <button type="button" class="btn btn-sm btn-warning">
                 &nbsp;Modifier
               </button></a>
        </div>
     </div>
    <div class="row titre_fiche" style="background-color:{{fiche.get_couleur}};">
        <div class="col textcenter" >
              <h2> {{ fiche.numero }}. {{ fiche.titre }}</h2>
        </div>
    </div>
    <div class="row-sm-12 justify-content-center">
        <div class="col-sm-12  fiche_tags">
            <p class="textright"> 
  {% if fiche.tags.names  %}Mots-clés:
           {% for tag in fiche.tags.names %}
            {{tag}}{%if not forloop.last%}, {%endif%}
           {% endfor %}
           {% endif %}  </p>
        </div>
    </div>
  
    <nav class="nav nav-tabs">
      <a class="nav-item nav-link active" href="#p1" data-toggle="tab">Fiche pratique</a>
      <a class="nav-item nav-link" href="#ateliers" data-toggle="tab">Ateliers</a>
      <a class="nav-item nav-link" href="#p3" data-toggle="tab">Discussion</a>
      <a class="nav-item nav-link" href="#p4" data-toggle="tab">En savoir plus...</a>
    </nav>

<div class="tab-content">
  <div class="tab-pane fade show active" id="p1">
    <div class="contenu fiche">
        {% if fiche.objectif%}
        <div class="row">
            <div class="col">
                <p class="fiche_objectif">Objectif : {{ fiche.objectif |safe}}</p>
            </div>
        </div>
        {% endif %}

        <div class="row">
            <div class="col">
               {{ fiche.contenu |safe}}
            </div>
        </div>
    </div>
  </div>

<div class="tab-pane fade" id="ateliers">
    <div class="contenu atelier">
        <div class="col textcenter">
            {%if request.user.is_authenticated %}
            <a href="{% url 'fiches:ajouterAtelier' fiche_slug=fiche.slug%}">
               <button type="button" class="btn btn-sm btn-warning">
                <i class="fa fa-plus"></i> Ajouter un atelier
               </button></a>
            {% endif %}
        </div>
    {% for atelier in ateliers %}
        <div class="row atelier_list" id="atelier{{atelier.slug}}">
        <div class="col">
            {% include 'fiches/atelier_template.html' with atelier=atelier %}
        </div>
        </div>
        {% if not forloop.last %}
    <hr>{% endif %}
    {% endfor %}
    </div>
</div>

<div class="tab-pane fade" id="p3">
    <div class="contenu commentaires discussion_fiche">
    <div id="idConversation">
    {% for comment in commentaires %}
        <div class="row {% if comment.auteur.id == request.user.id %} msg-auteur  {%else%} msg-destinataire{%endif%}">

            <div class="col-sm-3 col-md-3 col-lg-2">
               <p class="infos  textepetit">{{ comment.date_creation|date:"d/m/Y, G:i" }}{% ifchanged %}, {{comment.auteur_comm}}{% endifchanged %}</p>
            </div>
            <div class=" col-sm-9 col-md-9 col-lg-10 message ">
                    <div class="col">{{ comment.commentaire|safe|url}}</div>
            </div>
        </div>
    {% endfor %}
    </div>
        <script>
        var messageBody = document.querySelector('#idConversation');
        messageBody.scrollTop = idConversation.scrollHeight - idConversation.clientHeight;
    </script>
    <div>
            <input type="hidden" name="Nouveau Message" value="{{ message }}">

        <div>
{%if request.user.is_authenticated %}
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="Nouveau Message" value="{{ message_defaut }}">
            {% include 'form_template3.html' with boutonAnnuler=False %}

        </form>
{% else %}
            <p>(Vous devez vous connecter pour poster des commentaires)</p>
{% endif %}
        </div>

    </div>
  </div>
</div>



    <div class="tab-pane fade" id="p4">
        <div class="contenu ensavoirplus">
            <div class="row">
                <div class="col">
                   {{ fiche.en_savoir_plus |safe}}
                </div>
            </div>
        </div>
    </div>


</div>

    <script>
    getElementById("id_commentaire_iframe").height = "150px"
</script>


{% endblock %}